apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogQ2VwaAogIG1ldHJpY3NfcGF0aDogL21ldHJpY3MKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czoKICAgICAgLSA0My4yMjkuMjguNTg6OTI4MwpyZW1vdGVfd3JpdGU6CiAgLSB1cmw6ICJodHRwOi8vaW5mbHV4ZGIxLTgubW9uaXRvcmluZy5zdmMuY2x1c3Rlci5sb2NhbDo4MDg2L2FwaS92MS9wcm9tL3dyaXRlP2RiPXByb21ldGhldXMiCgpyZW1vdGVfcmVhZDoKICAtIHVybDogImh0dHA6Ly9pbmZsdXhkYjEtOC5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODYvYXBpL3YxL3Byb20vcmVhZD9kYj1wcm9tZXRoZXVzIg==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring